name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  precommit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0

  build:
    runs-on: ubuntu-latest
    needs:
      - precommit
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: eifinger/setup-rye@v4
      with:
        version: 'latest'
    - name: Install dependencies
      run: |
        rye sync
    - name: Build package
      run: |
        rye build

  lints:
    runs-on: ubuntu-latest
    needs:
      - precommit
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: eifinger/setup-rye@v4
        with:
          version: 'latest'
      - name: Make lints
        run: |
          rye lint      

  tests:
    runs-on: ubuntu-latest
    needs:
      - precommit
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: eifinger/setup-rye@v4
        with:
          version: 'latest'
      - name: Run tests
        run: |
          rye test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
